### ISSUE TITLE
Ship planner issue

### ISSUE THREAD

**Issue by brematy** [HealYouDown/flandria#17]
Ship planner is not working, I cannot select the sea level and it let me put only 1 point, can you fix this?
Thanks.

**Comment by HealYouDown** [comment]
Hey,

I just saw that you opened an issue, so sorry for the late response.

Ship planner works fine for me in Mozilla Firefox and Chrome. What browser are you using?

Greets,
Jeremy

**Comment by brematy** [comment]
Hi I'm using Chrome, adblock off, same issue with Microsoft Edge.
Looks like it works only when I select lv.40 or more.
From lv.1 to 39 nothing happens.

Il giorno mer 17 feb 2021 alle ore 21:10 Jeremy <notifications@github.com>
ha scritto:
